# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 03:17
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hi',
            name='sender',
            field=models.ManyToManyField(editable=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
