# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 04:15
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('his', '0003_hi_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hi',
            name='sender',
        ),
        migrations.AddField(
            model_name='hi',
            name='sender',
            field=models.ForeignKey(default=1, editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
