# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-09 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('his', '0005_auto_20170205_0421'),
    ]

    operations = [
        migrations.AddField(
            model_name='hi',
            name='hi',
            field=models.CharField(default='hi', editable='False', max_length=200),
        ),
    ]
